### ISSUE TITLE
Build Config never ran

### ISSUE THREAD

**Issue by hupiper** [kevchu3/azure-buildagent-container#5]
Error reported in diagnostic logs. Please examine the log for more details.
- /opt/app-root/app/_diag/Agent_20220730-163828-utc.log
VS30063: You are not authorized to access https://dev.azure.com.

**Comment by kevchu3** [comment]
I'm curious whether your token is working.  Can you rsh into your pod and run the following command adhoc to see if it works?
```
/opt/app-root/app/config.sh --unattended --url https://dev.azure.com/myOrg --auth pat --token myToken --pool default --agent myOCPAgent --acceptTeeEula
```

**Comment by hupiper** [comment]
I think this might have been the problem - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#confirm-the-user-has-permission. I only have one pool where I am listed as a user of the pool. We also need to make sure that people are using the value of the PAT and not the name of the PAT in the Dockerfile.
